### ISSUE TITLE
cmake 폴더 경로

### ISSUE THREAD

**Issue by s5kywa1k3r** [Konkuk-Grad/Microbench#17]
cmake 폴더 경로 적어주세요.

issue 테스트용이기도 하고 각자 폴더명 확실히도 할겸 알려주신분이나 이미 master에 merged 되신 분도 적어주시면 감사하겠습니다.

**Comment by spark-1** [comment]
CMakeLists.txt에 추가적으로
add_library(ipc STATIC mbti_ipc/mbti_ipc.c )
add_library(ipc STATIC mbti_ipc/mbti_mq*.c )
aux_source_directory(mbti_ipc IPC_SRC)
add_executable(mbti.out mbti_main.c ${SIGNAL_SRC} ${IPC_SRC})
이런식으로 적어 놓는건가요?

**Comment by s5kywa1k3r** [comment]
add_library 두 줄은 상관 없고 사실 aux_source부터 add_executable을 위하여 각 폴더명을 요청한 것입니다.
